version: '3.1'

services:
  php:
    build:
      context: ./
    ports:
      - 81:80
    volumes:
      - ./sources:/var/www/html/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sources/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 82:8080
